fix(l1): don't return an error if `forkChoiceUpdate` contains null `PayloadAttributes` (#1543)
**Motivation**
When we receive a payload with null payload attributes we return an
error: `Could not parse params invalid type: null, expected struct
PayloadAttributesV3`, when this is perfectly acceptable behaviour

**Description**
* Parse payload attributes as `Option<PayloadAttributes>` instead of
just `PayloadAttributes`
<!-- A clear and concise general description of the changes this PR
introduces -->

<!-- Link to issues: Resolves #111, Resolves #222 -->

Closes #issue_number